version: "3"
services:
  mongodb-service:
    image: mongo
    container_name: mongodb-service
    ports:
      - 27017:27017
    networks:
      - NETWORK_EXAM
    volumes:
      - VOLUME_EXAM:/mongodb
  backend:
    image: backend-app
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb-service 
    networks:
      - NETWORK_EXAM
  frontend:
    image: frontend-app
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend 
    networks:
      - NETWORK_EXAM
  

volumes:
  VOLUME_EXAM:
networks:
  NETWORK_EXAM:
    driver: bridge