version: '3'
services:
  mongodb-service:
    image: mongo
    volumes:
      - data:/data/db
    container_name: mongodb-service
    ports:
      - 27017:27017
  
  backend:
    image: localhost:5001/backend
    container_name: backend
    ports:
      - 5000:5000
    depends_on:
      - mongodb-service
  

  frontend:
    image: localhost:5001/frontend
    container_name: frontend
    ports:
      - 3000:80
    depends_on:
      - backend


volumes:
  data:
   